// Title: Potential LSASS Memory Dump
// Description: Detects suspicious processes accessing LSASS memory, which might indicate credential dumping (e.g., Mimikatz).
// Severity: High
// Category: Credential Access
// MITRE ATT&CK: T1003.001
// Author: TheHiddenOwl

DeviceProcessEvents
| where (FileName =~ @"procdump.exe" and ProcessCommandLine has @"lsass")
    or (FileName =~ @"comsvcs.dll" and ProcessCommandLine has_all (@"MiniDump", @"lsass"))
| union (
    DeviceEvents
    | where ActionType == @"OpenProcessApiCall"
    | where FileName !in~ (@"msmpeng.exe", @"mrt.exe", @"googleupdate.exe")
    // Looking for access to lsass.exe process
    | where TargetProcessFileName =~ @"lsass.exe"
)
| project TimeGenerated, DeviceName, FileName, ProcessCommandLine, InitiatingProcessFileName, TargetProcessFileName
